# Kubiq Services Configuration
# Format: service-name=endpoint-url
# Last updated: 2026-01-14T16:47:22.259Z

app-1=http://localhost:3000/app-1
app-2=http://localhost:3000/app-2
app-3=https://dns-abc/app-3
app-4=https://dns-def/app-4|abc:value1|def:value2
