apiVersion: v1
kind: Namespace
metadata:
  name: kubiq-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: kubiq-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:latest
        ports:
        - containerPort: 8123
          name: http
        - containerPort: 9000
          name: native
        env:
        - name: CLICKHOUSE_DB
          value: kubiq
        - name: CLICKHOUSE_USER
          value: default
        - name: CLICKHOUSE_PASSWORD
          value: "kubiq123"
        - name: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
          value: "1"
        volumeMounts:
        - name: clickhouse-data
          mountPath: /var/lib/clickhouse
      volumes:
      - name: clickhouse-data
        nfs:
          server: "NFS_SERVER_IP"
          path: /clickhouse-data
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: kubiq-system
spec:
  type: NodePort
  selector:
    app: clickhouse
  ports:
  - port: 8123
    name: http
    targetPort: 8123
    nodePort: 30123
  - port: 9000
    name: native
    targetPort: 9000
